// Support requests from the HR support response log (Group HR & GS), used as starting data in local test mode.
export const SEED_SUPPORT = [
 {
  "id": "sr-hrm-001",
  "ref": "SR-0001",
  "function": "hrm",
  "requester": "Wanza Logistics PLC",
  "category": "Policy / Governance",
  "description": "Policy / Governance",
  "priority": "Normal",
  "requested": "2026-07-15",
  "status": "Open",
  "responded": "2026-08-08",
  "action": "Management by law shared; to GM, FFD Manual Development, New Employee onboarding manual, Succession Planning Manual Employee transport Proposal, Employee caftrial Proposal , HR Administration Policy review",
  "respondedBy": "CHRO with leads",
  "evidence": "Email",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-002",
  "ref": "SR-0002",
  "function": "hrm",
  "requester": "Wanza Logistics PLC",
  "category": "Recruitment / Talent",
  "description": "Recruitment for top level and critical roles",
  "priority": "Normal",
  "requested": "2026-09-15",
  "status": "Responded",
  "responded": "2026-10-10",
  "action": "Sales opration specilalist , key Account excutive, enterprise sales specialist",
  "respondedBy": "Recruitment / Talent",
  "evidence": "ERP",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-003",
  "ref": "SR-0003",
  "function": "hrm",
  "requester": "Wanza Logistics PLC",
  "category": "Learning & Development",
  "description": "Training",
  "priority": "Normal",
  "requested": "2026-09-15",
  "status": "Responded",
  "responded": "2026-09-30",
  "action": "Financial Acumen for Non-Financial Leaders, People and culture training, customer exprince,Sales Strategy & CRM, OKR Training & Cascade for Department Leaders",
  "respondedBy": "Learning & Development",
  "evidence": "ERP",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-004",
  "ref": "SR-0004",
  "function": "hrm",
  "requester": "Wanza Logistics PLC",
  "category": "Facilities / Administration",
  "description": "Facility Support",
  "priority": "Normal",
  "requested": "2026-09-16",
  "status": "Responded",
  "responded": "2026-10-01",
  "action": "Transfer of vehicles from wagwago to wanza for capital contribution, House rent for new opening branches, Transfer of loan to capital contribution in legal framework,",
  "respondedBy": "FFD",
  "evidence": "ERP",
  "followUp": false,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-005",
  "ref": "SR-0005",
  "function": "hrm",
  "requester": "Niyat Consultancy",
  "category": "Policy / Governance",
  "description": "Policy / Governance",
  "priority": "Normal",
  "requested": "2026-07-15",
  "status": "Open",
  "responded": "2026-08-08",
  "action": "Management by law shared; to GM, FFD Manual Development, New Employee onboarding manual, Succession Planning Manual, Employee transport Proposal, Employee caftrial Proposal , HR Administration Policy review",
  "respondedBy": "CHRO with leads",
  "evidence": "ERP",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-006",
  "ref": "SR-0006",
  "function": "hrm",
  "requester": "Niyat Consultancy",
  "category": "Recruitment / Talent",
  "description": "Recruitment for top level and critical roles",
  "priority": "Normal",
  "requested": "2026-09-15",
  "status": "Open",
  "responded": "2026-10-10",
  "action": "Business development Officer, Sales Suppervisor, Sales representative",
  "respondedBy": "Recruitment / Talent",
  "evidence": "ERP",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-007",
  "ref": "SR-0007",
  "function": "hrm",
  "requester": "Niyat Consultancy",
  "category": "Learning & Development",
  "description": "Training",
  "priority": "Normal",
  "requested": "2026-09-15",
  "status": "Open",
  "responded": "2026-09-30",
  "action": "Financial Acumen for Non-Financial Leaders, People and culture training, customer exprince,Sales Strategy & CRM",
  "respondedBy": "Learning & Development",
  "evidence": "ERP",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-008",
  "ref": "SR-0008",
  "function": "hrm",
  "requester": "Niyat Consultancy",
  "category": "Facilities / Administration",
  "description": "Facility Support",
  "priority": "Normal",
  "requested": "2026-09-16",
  "status": "Open",
  "responded": "2026-10-01",
  "action": "man power list update for BPM Team,",
  "respondedBy": "FFD",
  "evidence": "ERP",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-009",
  "ref": "SR-0009",
  "function": "hrm",
  "requester": "Wagwago Electric",
  "category": "Policy / Governance",
  "description": "Policy / Governance",
  "priority": "Normal",
  "requested": "2026-07-15",
  "status": "Open",
  "responded": "2026-08-08",
  "action": "Management by law shared; to GM, FFD Manual Development, New Employee onboarding manual, Succession Planning Manual, Employee transport Proposal, Employee caftrial Proposal , HR Administration Policy review , HR & FFD Dashboard Developed",
  "respondedBy": "CHRO with leads",
  "evidence": "ERP",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-010",
  "ref": "SR-0010",
  "function": "hrm",
  "requester": "Wagwago Electric",
  "category": "Recruitment / Talent",
  "description": "Recruitment for top level and critical roles",
  "priority": "Normal",
  "requested": "2026-09-15",
  "status": "Open",
  "responded": "2026-10-10",
  "action": "Key Accoun section head",
  "respondedBy": "Recruitment / Talent",
  "evidence": "ERP",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-011",
  "ref": "SR-0011",
  "function": "hrm",
  "requester": "Wagwago Electric",
  "category": "Learning & Development",
  "description": "Training",
  "priority": "Normal",
  "requested": "2026-09-15",
  "status": "Open",
  "responded": "2026-09-30",
  "action": "Financial Acumen for Non-Financial Leaders, People and culture training, customer exprince,Sales Strategy & CRM, OKR Training & Cascade for Department Leaders",
  "respondedBy": "Learning & Development",
  "evidence": "ERP",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-012",
  "ref": "SR-0012",
  "function": "hrm",
  "requester": "Wagwago Electric",
  "category": "Facilities / Administration",
  "description": "Facility Support",
  "priority": "Normal",
  "requested": "2026-09-16",
  "status": "Open",
  "responded": "2026-10-01",
  "action": "Manager Vehicle Rental Support, Medical & Life Insurance Guidance, Transfer of vehicles from wagwago, House Rent – New Office Relocation,",
  "respondedBy": "FFD",
  "evidence": "ERP",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-013",
  "ref": "SR-0013",
  "function": "hrm",
  "requester": "Wagwago Corporate Office",
  "category": "Policy / Governance",
  "description": "Policy / Governance",
  "priority": "Normal",
  "requested": "2026-07-15",
  "status": "Open",
  "responded": "2026-08-08",
  "action": "Management by law shared; to GM, FFD Manual Development, New Employee onboarding manual, Succession Planning Manual, Employee transport Proposal, Employee caftrial Proposal , HR Administration Policy review , HR & FFD Dashboard Developed, Employee Wellness, Mothers’ Room Policy & Safety Manual Developed, HR Interface Manual Developed",
  "respondedBy": "CHRO with leads",
  "evidence": "ERP",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-014",
  "ref": "SR-0014",
  "function": "hrm",
  "requester": "Wagwago Corporate Office",
  "category": "Recruitment / Talent",
  "description": "Recruitment for top level and critical roles",
  "priority": "Normal",
  "requested": "2026-09-23",
  "status": "Open",
  "responded": "2026-10-10",
  "action": "All Requested Manpower fulfil by (recurtment, promotion, transfer) that include CTO 2 postions, Audit 2 postions, Marketing 4 postions, Finance 4 postion,",
  "respondedBy": "Recruitment / Talent",
  "evidence": "ERP",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-015",
  "ref": "SR-0015",
  "function": "hrm",
  "requester": "Wagwago Corporate Office",
  "category": "Learning & Development",
  "description": "Training",
  "priority": "Normal",
  "requested": "2026-09-15",
  "status": "Open",
  "responded": "2026-09-30",
  "action": "Financial Acumen for Non-Financial Leaders, People and culture training, Sales Strategy & CRM, TNA Conducted & Aligned with Stakeholders",
  "respondedBy": "Learning & Development",
  "evidence": "ERP",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-016",
  "ref": "SR-0016",
  "function": "hrm",
  "requester": "Wagwago Corporate Office",
  "category": "Facilities / Administration",
  "description": "Facility Support",
  "priority": "Normal",
  "requested": "2026-09-16",
  "status": "Open",
  "responded": "2026-10-01",
  "action": "Car Insurance & Maintenance Completed, Medical & Life insurance renewed, transport service assessment conducted, Cafeteria service proposal Developed, House Rent – Office Arrengment conducted, Annual Satsfaction servey, Employer Branding at Ethiojobs,",
  "respondedBy": "FFD",
  "evidence": "ERP",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-017",
  "ref": "SR-0017",
  "function": "hrm",
  "requester": "GET PLC",
  "category": "Policy / Governance",
  "description": "Policy / Governance",
  "priority": "Normal",
  "requested": "2026-07-15",
  "status": "Open",
  "responded": "2026-08-08",
  "action": "Management by law shared; to CEO, FFD Manual Development, New Employee onboarding manual, Succession Planning Manual, Employee transport Proposal, Employee caftrial Proposal , HR Administration Policy review , Employee Wellness, Mothers’ Room Policy & Safety Manual Developed, HR Interface Manual Developed",
  "respondedBy": "CHRO with leads",
  "evidence": "ERP",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-018",
  "ref": "SR-0018",
  "function": "hrm",
  "requester": "GET PLC",
  "category": "Recruitment / Talent",
  "description": "Recruitment for top level and critical roles",
  "priority": "Normal",
  "requested": "",
  "status": "Open",
  "responded": "",
  "action": "",
  "respondedBy": "",
  "evidence": "",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-019",
  "ref": "SR-0019",
  "function": "hrm",
  "requester": "GET PLC",
  "category": "Learning & Development",
  "description": "Training",
  "priority": "Normal",
  "requested": "2026-09-15",
  "status": "Open",
  "responded": "2026-09-30",
  "action": "People and Culture training for HR Employee,",
  "respondedBy": "",
  "evidence": "",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-020",
  "ref": "SR-0020",
  "function": "hrm",
  "requester": "GET PLC",
  "category": "Facilities / Administration",
  "description": "Facility Support",
  "priority": "Normal",
  "requested": "2026-09-16",
  "status": "Open",
  "responded": "2026-10-01",
  "action": "compliance management and intervention in office rental,",
  "respondedBy": "",
  "evidence": "",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-021",
  "ref": "SR-0021",
  "function": "hrm",
  "requester": "Trucksload Logistics Solutions PLC",
  "category": "Policy / Governance",
  "description": "Policy / Governance",
  "priority": "Normal",
  "requested": "2026-07-15",
  "status": "Open",
  "responded": "2026-08-08",
  "action": "Management by law shared; to CEO, FFD Manual Development, New Employee onboarding manual, Succession Planning Manual, Employee transport Proposal, Employee caftrial Proposal , HR Administration Policy review , Employee Wellness, Mothers’ Room Policy & Safety Manual Developed, HR Interface Manual Developed",
  "respondedBy": "CHRO with leads",
  "evidence": "ERP",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-022",
  "ref": "SR-0022",
  "function": "hrm",
  "requester": "Trucksload Logistics Solutions PLC",
  "category": "Recruitment / Talent",
  "description": "Recruitment for top level and critical roles",
  "priority": "Normal",
  "requested": "2026-09-23",
  "status": "Open",
  "responded": "2026-10-10",
  "action": "Key Account manager and Sales manager long list send",
  "respondedBy": "",
  "evidence": "",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-023",
  "ref": "SR-0023",
  "function": "hrm",
  "requester": "Trucksload Logistics Solutions PLC",
  "category": "Learning & Development",
  "description": "Training",
  "priority": "Normal",
  "requested": "2026-09-15",
  "status": "Open",
  "responded": "2026-09-30",
  "action": "customer exprince",
  "respondedBy": "",
  "evidence": "",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 },
 {
  "id": "sr-hrm-024",
  "ref": "SR-0024",
  "function": "hrm",
  "requester": "Trucksload Logistics Solutions PLC",
  "category": "Facilities / Administration",
  "description": "Facility Support",
  "priority": "Normal",
  "requested": "2026-09-16",
  "status": "Open",
  "responded": "2026-10-01",
  "action": "support in managerial car rental, car insurance and maintance",
  "respondedBy": "",
  "evidence": "",
  "followUp": true,
  "remarks": "",
  "createdBy": "Imported from HR support log",
  "createdAt": "2026-10-09T00:00:00.000Z",
  "updatedBy": "Imported from HR support log",
  "updatedAt": "2026-10-09T00:00:00.000Z"
 }
];
